Use string instead of label
But this leads to
```
error: failed to sync

Caused by:
  failed to create directory `/crates`

Caused by:
  Read-only file system (os error 30)

Error: Failed to vendor dependencies

Caused by:
    Failed to vendor sources with: exit status: 101
```