Vendor then remove absolute path
To work around both
```
error: failed to sync

Caused by:
  failed to create directory `/crates`

Caused by:
  Read-only file system (os error 30)

Error: Failed to vendor dependencies

Caused by:
    Failed to vendor sources with: exit status: 101
```
and then
```
ERROR: /Users/preston/git/bazel-experiment/BUILD:13:12: //:hello_world: invalid label '///Users/preston/git/bazel-experiment/crates/axum-0.5.6:axum' in element 0 of attribute 'deps' in 'rust_binary' rule: invalid package name '/Users/preston/git/bazel-experiment/crates/axum-0.5.6': package names may not start with '/'
ERROR: error loading package '': Package '' contains errors
INFO: Elapsed time: 0.051s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
FAILED: Build did NOT complete successfully (1 packages loaded)
```